name: Deploy Next.js to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: finanzas-ok-8c956
          install_components: "beta"

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker gcr.io

      - name: Docker Build
        run: docker build --platform=linux/amd64 -t gcr.io/finanzas-ok-8c956/finanzas-ok-web .

      - name: Push Docker Image
        run: docker push gcr.io/finanzas-ok-8c956/finanzas-ok-web:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy finanzas-ok-web \
            --image gcr.io/finanzas-ok-8c956/finanzas-ok-web:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --clear-env-vars \
            --set-secrets BACKEND_API=backend-api:latest

      - name: Notify Discord on Success
        if: success()
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "🚀 Finanzas Web Deployment to Cloud Run was **successful**!"}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Notify Discord on Failure
        if: failure()
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "❌ Finanzas Web Deployment to Cloud Run **failed**. Please check logs."}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
